### ISSUE TITLE
How to evaluate the tracker on OTB99

### ISSUE THREAD

**Issue by lawpdas** [fredfung007/snlt#11]
I have run your tracker on OTB99 and evaluated it with OTB-toolkit. But it gave 0.573 succ. and 0.746 prec., it also gave different results on other trackers. Could you help me?
![SOTA_AUC](https://user-images.githubusercontent.com/5070053/130343093-4fa1625f-1288-4d98-9f99-9270f994d96a.jpg)

**Comment by lizxko2009** [comment]
Hello, I have some problems when running the code. I would like to ask what CUDA version and Pytorch version you are using. Thank you for your reply in your busy schedule

**Comment by fredfung007** [comment]
I used CUDA 11 with PyTorch 1.9.

**Comment by fredfung007** [comment]
OTB-99-LANG is slightly different from the normal OTB-100.

**Comment by fredfung007** [comment]
It is also worth noticing that the OTB-99 videos were corrupted. I used the OTB-100 videos paired with OTB-99 language annotations.

**Comment by lawpdas** [comment]
Thanks for your reply! 
But I don't know why it gives different results on other trackers. These trackers are evaluated with OTB100, and I use their raw results directly.
What toolkit you are using for evaluation? PYSOT version or matlab version? I use the matlab version.

**Comment by fredfung007** [comment]
Evaluation code is given in this repo. ope.py

**Comment by lawpdas** [comment]
Many thanks!
