### ISSUE TITLE
About embedding dimension?

### ISSUE THREAD

**Issue by laisimiao** [fredfung007/snlt#12]
https://github.com/fredfung007/snlt/blob/cae456416898e2f694bf7511d7d7d0a267b82c69/region_proposal_network/multi_nl_rpn.py#L31-L33

If embedding dimension is not 768(256x3), so we need use adjustlayer to adjust output channel of correlationed feature to meet the 1/3 of embedding dimension?

**Comment by fredfung007** [comment]
Yes, I think that should be the direction. For GloVe and HGLMM versions, we used the same embeddings (256d) for all l2,3,4 rpns.
