### ISSUE TITLE
Where to download OTB-99?

### ISSUE THREAD

**Issue by laisimiao** [fredfung007/snlt#8]
Do we just need to download language description? Could you please tell us where to download OTB-99 dataset?

**Comment by laisimiao** [comment]
Refer to [https://github.com/QUVA-Lab/lang-tracker](https://github.com/QUVA-Lab/lang-tracker)

**Comment by fredfung007** [comment]
I asked the original authors a while ago. You can directly reach out to them.

**Comment by 201722111112027** [comment]
The link provided cannot seem to be opened. Have you found the data set? Can you share it?
