### ISSUE TITLE
about raw results

### ISSUE THREAD

**Issue by lawpdas** [fredfung007/snlt#9]
Hi,
I want to cite this work and make some comparisons. Could you provide the raw results? 
I also notice that you have included TNL2k in your code.
Have you re-trained the model using this dataset?
Could you provide the new model and the evaluation result on this dataset?

**Comment by fredfung007** [comment]
I didn't train the model on TNL2K. I will upload the raw results once I get back from my internship. (around September)

**Comment by fredfung007** [comment]
BTW, the TNL2K have a lot of scene cut cases, and the current model is not performing very well on those cases.
